# Generated by Django 3.1.2 on 2021-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0003_policereg_userreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
