# Generated by Django 3.1.2 on 2021-04-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0004_userreg_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crime.policereg')),
            ],
        ),
    ]
