# Generated by Django 3.1.2 on 2021-04-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='fir_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timee', models.CharField(max_length=50)),
                ('c_date', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('charge', models.ImageField(upload_to='images/')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crime.policereg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crime.userreg')),
            ],
        ),
    ]
